---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "tandoor.fullname" . }}-encrypt
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/autogenerate: secret-key
stringData: {}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "tandoor.fullname" . }}-ldap-user
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: {{ .Values.ldap.user }}