apiVersion: v1
kind: Service
metadata:
  name: {{ include "tandoor.fullname" . }}
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
  - port: 8080
    targetPort: gunicorn
    name: gunicorn
    protocol: TCP
  selector:
    {{- include "tandoor.selectorLabels" . | nindent 4 }}
