apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inadyn.fullname" . }}-config
  labels:
    {{- include "inadyn.labels" . | nindent 4 }}
data:
  inadyn.conf.py: |-
    import os
    import sys

    print("Reading variables")
    user = os.environ["CLOUDFLARE_USER"]
    token = os.environ["CLOUDFLARE_TOKEN"]

    print("Generating output")
    generated = f"""
    # Create a unique custom API token with the following permissions:
    # -> Zone.Zone - Read, Zone.DNS - Edit.
    provider cloudflare.com {{ "{{" }}
        username = "{user}"
        password = "{token}"
        hostname = {{ .Values.domainName }}
    {{ "}}" }}
    """
    print("Writing to " + sys.argv[1])
    with open(sys.argv[1], 'w') as output:
        output.write(generated)
