apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inadyn.fullname" . }}
  labels:
    {{- include "inadyn.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "inadyn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inadyn.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-createconfig
          image: python:alpine3.19
          imagePullPolicy: IfNotPresent
          command:
            - python
            - /templates/ddclient.conf.py
            - /out/ddclient.conf
          env:
            - name: CLOUDFLARE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "inadyn.fullname" . }}-cloudflare
                  key: user
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "inadyn.fullname" . }}-cloudflare
                  key: api-token
          volumeMounts:
            - name: config
              mountPath: /out
            - name: configtemplate
              mountPath: /templates
              readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          image: "lscr.io/linuxserver/ddclient:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /etc
      volumes:
        - name: config
          emptyDir: {}
        - name: configtemplate
          configMap:
            name: {{ include "inadyn.fullname" . }}-config
            items:
              - key: ddclient.conf.py
                path: ddclient.conf.py
