apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inadyn.fullname" . }}
  labels:
    {{- include "inadyn.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "inadyn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inadyn.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-createconfig
          image: dinutac/jinja2docker:latest
          imagePullPolicy: IfNotPresent
          args:
            - /templates/inadyn.conf.j2
            - --format=json
            - ">"
            - /out/inadyn.conf
          env:
            - name: CLOUDFLARE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "inadyn.fullname" . }}-cloudflare
                  key: user
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "inadyn.fullname" . }}-cloudflare
                  key: api-token
          volumeMounts:
            - name: config
              mountPath: /out
            - name: conftemplate
              mountPath: /templates
              readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          image: "troglobit/inadyn:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
              - catinadyn
              - --check-config
          volumeMounts:
            - name: config
              mountPath: /etc
              subPath: inadyn.conf
      volumes:
        - name: config
          emptyDir: {}
        - name: configtemplate
          configMap:
            name: {{ include "inadyn.fullname" . }}-config
            items:
              - key: inadyn.conf.j2
                path: inadyn.conf.j2
