---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inadyn.fullname" . }}-conf
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-token
type: Opaque
stringData:
  user: {{ .Values.user }}
