apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "jellyfin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/linuxserver.io/jellyfin:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "{{ .Values.user.uid }}"
            - name: PGID
              value: "{{ .Values.user.gid }}"
            - name: JELLYFIN_PublishedServerUrl
              value: "https://{{ .Values.service.name }}.{{ .Values.ingress.domainName }}"
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/cache"
              name: "cache"
            {{ range .Values.smbMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{ end }}
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-config
        - name: "cache"
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-cache
        {{ range .Values.smbMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{ end }}
