---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  template:
    metadata:
      name: jellyfin
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8096
          protocol: TCP
        volumeMounts:
        - mountPath: /data/media
          name: jellyfin-media
          readOnly: True
        - mountPath: /config
          name: jellyfin-config
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
      volumes:
      - name: jellyfin-media
        persistentVolumeClaim:
          claimName: jellyfin-media
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config