apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/linuxserver.io/jellyfin:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/cache"
              name: "cache"
            {{ with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{ end }}
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-config
        - name: "cache"
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-cache
        {{ with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
