{{ range .Values.localMounts }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .localPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name }}
spec:
  storageClassName: smb
  volumeName: {{ .name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .size }}
{{ end }}