---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath  
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media 
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: "/volume1/media"
    server: <ADDRESS OF NFS SERVER>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi