apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "diun.fullname" . }}-data
  labels:
    {{- include "diun.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi