apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "lldap.fullname" . }}-db
spec:
  instances: 1
  storage:
    size: 1Gi

  managed:
    roles:
    - name: lldap
      createdb: true
      login: true