apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lldap.fullname" . }}-service
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  tls:
    - hosts:
        - 'lldap.{{ .Values.domainName }}'
      secretName: {{ include "lldap.fullname" . }}-ssl
  rules:
    - host: 'lldap.{{ .Values.domainName }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lldap.fullname" . }}-service
                port:
                  name: web
