apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lldap.fullname" . }}-data
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi