---
apiVersion: v1
kind: Namespace
metadata:
  name: testdest
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ldap-jwt
  namespace: testdest
  annotations:
    replicator.v1.mittwald.de/replicate-from: lldap/lldap-jwt
stringData: {}