---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lldap.fullname" . }}-secretauth
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lldap.fullname" . }}-secretauth
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lldap.fullname" . }}-secretauth
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lldap.fullname" . }}-secretauth
subjects:
  - kind: ServiceAccount
    name: {{ include "lldap.fullname" . }}-secretauth
    namespace: {{ .Release.Namespace }}

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "lldap.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "lldap.fullname" . }}-secretauth
  conditions:
    - namespaces:
        - "testdest"
---
apiVersion: v1
kind: Namespace
metadata:
  name: testdest
  labels:
    davidvh/secrets: ldap
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-credentials
  namespace: testdest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "lldap.fullname" . }}-secrets
  target:
    name: ldap-credentials
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: {{ include "lldap.fullname" . }}-credentials
      property: jwt-secret
