---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lldap.fullname" . }}-jwt
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: |
      davidvh/secrets=ldap
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/autogenerate: jwt-secret
data: {}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lldap.fullname" . }}-initial-password
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: admin