apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ include "lldap.fullname" }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  forceRegenerate: false
  data: {}
  fields:
    - fieldName: "jwt-secret"
      length: "32"
    - fieldName: "admin-pass"
      length: "10"