apiVersion: v1
kind: Secret
metadata:
  {{- $secretName := printf "%s-%s" (include "lldap.fullname" .) "credentials" }}
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- /* retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result */}}

  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- /* set $jwtSecret to existing secret data or generate a random one when not exists */}}
  {{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 32) }}
  jwt-secret: {{ $jwtSecret | quote }}
  {{- $adminPass := (get $secretData "admin-pass") | default (randAlphaNum 10) }}
  admin-pass: {{ $adminPass | quote }}