apiVersion: v1
kind: Service
metadata:
  name: {{ include "komga.fullname" . }}
  labels:
    {{- include "komga.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 25600
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "komga.selectorLabels" . | nindent 4 }}
