apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bookstack.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookstack.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "bookstack.fullname" . }}
          image: linuxserver/bookstack:{{ .Chart.AppVersion }}
          ports:
            - name: web
              containerPort: 80
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: APP_URL
              value: 'https://{{ .Values.service.name }}.{{ .Values.ingress.domainName }}'
            - name: DB_HOST
              value: {{ include "bookstack.fullname" . }}-db
            - name: DB_USER
              value: bookstack
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookstack.fullname" . }}-db-user
                  key: password
            - name: DB_DATABASE
              value: bookstack
            - name: AUTH_METHOD
              value: ldap
            - name: LDAP_SERVER
              value: {{ .Values.ldap.host }}
            - name: LDAP_BASE_DN
              value: ou=people,{{ .Values.ldap.dn }}
            - name: LDAP_DN
              value: uid={{ .Values.ldap.user }},ou=people,{{ .Values.ldap.dn }}
            - name: LDAP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookstack.fullname" . }}-ldap-user
                  key: password
            - name: LDAP_USER_FILTER
              value: (&(uid=$${user}))
            - name: LDAP_VERSION
              value: '3'
            - name: LDAP_ID_ATTRIBUTE
              value: uid
            - name: LDAP_EMAIL_ATTRIBUTE
              value: mail
            - name: LDAP_DISPLAY_NAME_ATTRIBUTE
              value: cn
            - name: LDAP_START_TLS
              value: 'false'
          volumeMounts:
            - mountPath: "/config"
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "bookstack.fullname" . }}-data