apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "bookstack.fullname" . }}-ldap-user
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: {{ .Values.ldap.user }}