{{- $chart := .Chart -}}
{{- $release := .Release }}
{{- range .Values.deployments }}
{{- $deployment := . }}
{{- range .containers }}
{{- $container := . }}
{{- range .endpoints }}
{{- $endpoint := . }}
{{- with .ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $deployment.name }}-{{ $container.name }}-{{ $endpoint.name }}
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    {{- with .homepage }}
    gethomepage.dev/enabled: {{ .enabled | default "true" | quote }}
    gethomepage.dev/name: {{ .name | quote }}
    gethomepage.dev/description: {{ .desc | quote }}
    gethomepage.dev/group: {{ .group | quote }}
    gethomepage.dev/icon: {{ .icon | default "mdi-docker" | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .hostname }}
      secretName: {{ $deployment.name }}-{{ $container.name }}-{{ $endpoint.name }}-ssl
  rules:
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $deployment.name }}-{{ $container.name }}
                port:
                  name: {{ $endpoint.name }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
