apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ include "authelia.fullname" . }}-secrets
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: JWT_TOKEN
      encoding: "base64"
      length: 32
    - fieldName: SESSION_ENCRYPTION_KEY
      encoding: "base64"
      length: 32
    - fieldName: STORAGE_ENCRYPTION_KEY
      encoding: "base64"
      length: 32
    - fieldName: LDAP_PASSWORD
      encoding: "base64"
      length: 20
