apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: "https://github.com/davidvh/argocd.git"
    targetRevision: HEAD
    path: charts/bookstack
    helm:
      parameters:
        - name: ingress.domainName
          value: {{ .Values.host.domainName }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: bookstack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
