{{ range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.fullname" $ }}-{{ .name }}
  labels:
    {{- include "samba.labels" $ | nindent 4 }}
spec:
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
---
{{ end }}