apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kavita.fullname" . }}
  labels:
    {{- include "kavita.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kavita.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "kavita.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "lscr.io/linuxserver/kavita:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "{{ .Values.user.uid }}"
            - name: PGID
              value: "{{ .Values.user.gid }}"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            failureThreshold: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            {{ range .Values.smbMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{ end }}
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: {{ include "kavita.fullname" . }}-config
        {{ range .Values.smbMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{ end }}
