apiVersion: v1
kind: Service
metadata:
  name: {{ include "kavita.fullname" . }}
  labels:
    {{- include "kavita.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kavita.selectorLabels" . | nindent 4 }}
