apiVersion: v1
data:
  config.yml: |-
    upstream:
      default: {{ .Values.upstream | toYaml | nindent 8 }}
    {{- if .Values.customDns }}
    customDNS:
      mapping: {{ .Values.customDns | toYaml | nindent 8 }}
    {{- end }}
    {{- if .Values.customUpstream }}
    conditional:
      mapping: {{ .Values.customUpstream | toYaml | nindent 8 }}
    {{- end }}
    blocking:
      blackLists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - ads
    port: 53

kind: ConfigMap
metadata:
  name: {{ include "blocky.fullname" . }}-config