---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blocky.serviceAccountName" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "blocky.serviceAccountName" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - "services"
    - "namespaces"
    verbs:
    - "list"
    - "watch"
  - apiGroups:
    - "extensions"
    - "networking.k8s.io"
    resources:
    - "ingresses"
    verbs:
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "blocky.serviceAccountName" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "blocky.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "blocky.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
