apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wgeasy.fullname" . }}-admin-password
  labels:
    {{- include "wgeasy.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: admin