---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wgeasy.fullname" . }}-ui
  labels:
    {{- include "wgeasy.labels" . | nindent 4 }}
spec:
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 51821
  selector:
    {{- include "wgeasy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wgeasy.fullname" . }}-wireguard
  labels:
    {{- include "wgeasy.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  publishNotReadyAddresses: false
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    {{- include "wgeasy.selectorLabels" . | nindent 4 }}