# See https://github.com/argoproj/argoproj-deployments/blob/master/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

namespace: argocd
