apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "maildev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maildev.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /usr/src/app/bin/maildev
          env:
            - name: MAILDEV_DISABLE_WEB
              value: 'true'
            - name: MAILDEV_HTTPS
              value: 'false'
            - name: MAILDEV_WEB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "maildev.fullname" . }}-web
                  key: username
            - name: MAILDEV_WEB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "maildev.fullname" . }}-web
                  key: password
            - name: MAILDEV_SMTP_PORT
              value: '1025'
            - name: MAILDEV_WEB_PORT
              value: '1080'
            - name: MAILDEV_OUTGOING_HOST
              value: {{ .Values.smtp.host }}
            - name: MAILDEV_OUTGOING_PORT
              value: '{{ .Values.smtp.port }}'
            - name: MAILDEV_OUTGOING_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "maildev.fullname" . }}-outgoing
                  key: username
            - name: MAILDEV_OUTGOING_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "maildev.fullname" . }}-outgoing
                  key: password
            - name: MAILDEV_OUTGOING_SECURE
              value: 'true'
          args:
            - '--verbose'
            - '--outgoing-secure'
            - '--auto-relay'
          image: 'maildev/maildev:{{ .Chart.AppVersion }}'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1080
          ports:
            - containerPort: 1080
              name: web
              protocol: TCP
            - containerPort: 1025
              name: smtp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1080
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /etc/maildev
              name: auto-relay-rules
              subPath: auto-relay-rules.json
      securityContext: {}
      serviceAccountName: default
      volumes:
        - configMap:
            items:
              - key: auto-relay-rules.json
                path: auto-relay-rules.json
            name: {{ include "maildev.fullname" . }}-relay-rules
          name: auto-relay-rules
