---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "maildev.fullname" . }}-outgoing
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: {{ .Values.smtp.user }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "maildev.fullname" . }}-web
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/length: "10"
    secret-generator.v1.mittwald.de/autogenerate: password
stringData:
  username: admin