apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ spec.destination.server }}
    namespace: default
  project: infrastructure
  source:
    path: charts/argo-cd
    repoURL: https://github.com/dahenr/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true