apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  tls:
    - hosts:
        - 'argocd.{{ .Values.host.domainName }}'
      secretName: argocd-server-tls # as expected by argocd-server
  rules:
    - host: 'argocd.{{ .Values.host.domainName }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd
                port:
                  name: web

