apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "Kubernetes management"
    gethomepage.dev/group: "Backend"
    gethomepage.dev/icon: "argocd.png"
spec:
  tls:
    - hosts:
        - 'argocd.{{ .Values.host.domainName }}'
      secretName: argocd-server-tls # as expected by argocd-server
  rules:
    - host: 'argocd.{{ .Values.host.domainName }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http

