apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: "https://charts.goauthentik.io"
    targetRevision: 2023.3.1
    helm:
      values: |
        authentik:
          secret_key: {{ .Values.authentik.secret_key }}
          error_reporting:
            enabled: true
          postgresql:
            password: {{ .Values.authentik.db_password }}

        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
            kubernetes.io/tls-acme: "true"
          tls:
            - hosts:
                - '*.{{ .Values.host.domainName }}'
              secretName: cert-authentik
          hosts:
            - host: authentik.{{ .Values.host.domainName }}
              paths:
                - path: "/"
                  pathType: Prefix

        postgresql:
          enabled: true
          postgresqlPassword: {{ .Values.authentik.db_password }}
        redis:
          enabled: true
    chart: authentik
  destination:
    server: {{ .Values.destination.server }}
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
