apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - akoutpost.{{ .Values.host.domainName }}
      secretName: cert-akoutpost
  rules:
    - host: akoutpost.{{ .Values.host.domainName }}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-authentik-embedded-outpost
                port:
                  number: 9000
