---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-token
type: Opaque
stringData:
  email: {{ .Values.cloudflare.email }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: {{ .Values.cloudflare.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token