apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: 'https://github.com/davidvh/argocd.git'
    path: charts/diun
    helm:
      parameters:
        - name: smtp.from
          value: {{ .Values.cloudflare.email }}
        - name: smtp.to
          value: {{ .Values.cloudflare.email }}
    targetRevision: HEAD
  destination:
    server: {{ .Values.destination.server }}
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
