apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maildev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: 'https://github.com/davidvh/argocd.git'
    path: charts/maildev
    targetRevision: HEAD
    helm:
      parameters:
        - name: smtp.user
          value: {{ .Values.smtp.user }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: maildev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
