apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
    source:
    repoURL: 'https://mariadb-operator.github.io/mariadb-operator'
    targetRevision: 0.24.0
    chart: mariadb-operator
  destination:
    server: {{ .Values.destination.server }}
    namespace: mariadb-operator
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
