apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.9.0
    chart: ingress-nginx
    helm:
      parameters:
        - name: "controller.ingressClassResource.default"
          value: "true"
        - name: controller.allowSnippetAnnotations
          value: 'true'
        - name: controller.service.loadBalancerIP
          value: {{ .Values.host.address }}
        - name: controller.service.annotations.metallb\.universe\.tf/allow-shared-ip
          value: cluster
  destination:
    server: {{ .Values.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
