apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: "https://cloudnative-pg.github.io/charts"
    targetRevision: 0.20.0
    chart: cloudnative-pg
  destination:
    server: {{ .Values.destination.server }}
    namespace: cnpg-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
