apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: 'https://helm.mittwald.de'
    targetRevision: 2.9.2
    chart: kubernetes-replicator
  destination:
    server: {{ .Values.destination.server }}
    namespace: kubernetes-replicator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
