apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.destination.project }}
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 22.0.0
    chart: traefik
  destination:
    server: {{ .Values.destination.server }}
    namespace: traefik-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
