host:
  domainName: duckdns.org

duckdns:
  token: TODO
  email: todo@email.com

authentik:
  secret_key: TODO
  db_password: TODO

destination:
  server: https://kubernetes.default.svc
  project: default