host:
  domainName: mydomain
  address: 127.0.0.1

# Describe the local network to enable routing
localNetwork:
  domain: "" # The local domain of your network
  dns: "" # The IP address of your network DNS provider (usually your router)
  staticHosts: {} # A map of any static routes (e.g. `router.local: 127.0.0.1`)

cloudflare:
  email: email@email.com
  secret: TODO

ldap:
  dn: "dc=example,dc=com"

homepage:
  bookmarks:
    - Developer:
        - Github:
            - abbr: davidvh
              href: https://github.com/davidvh/argocd
  externalServices:
    - Network:
        - Slashdot:
            href: https://www.slashdot.org
            description: Slashdot
        - TrueNAS:
            href: https://www.truenas.com/
            description: TrueNAS
  widgets:
    - search:
        provider: duckduckgo
        target: _blank

destination:
  server: https://kubernetes.default.svc
  project: default