apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.service.name }}
spec:
 selector:
   matchLabels:
     app: {{ .Values.service.name }}
 template:
   metadata:
     labels:
       app: {{ .Values.service.name }}
   spec:
     containers:
       - name: {{ .Values.service.name }}
         image: traefik/whoami
         ports:
           - name: web
             containerPort: 80