apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Values.auth.host }}.{{ .Values.auth.namespace }}.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.auth.host }}.{{ .Values.ingress.domainName }}?rm=$request_method
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "WhoAmI"
    gethomepage.dev/description: "User diagnostics"
    gethomepage.dev/group: "Backend"
    gethomepage.dev/icon: "mdi-account-check"
spec:
  tls:
    - hosts:
        - '{{ .Values.service.name }}.{{ .Values.ingress.domainName }}'
      secretName: cert-{{ .Values.service.name }}
  rules:
    - host: '{{ .Values.service.name }}.{{ .Values.ingress.domainName }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  name: web
